env:
    rclone_config: "ENCRYPTED[81f2ea42a1bb72f5514f01604e25bb9057eb0b6f1b0f5a18434dd7175df07619a880e75ecb9597e10e69fba44553fe84]"

task:
    name: nusantara
    timeout_in: 120m
    container:
      image: inok2341/anu:latest
      cpu: 8
      memory: 32G      

    monitor_background_script:
      - ./monitor
      - df -h && free -h && nproc && cat /etc/os* && env
      - rclone copy inok:nusantara/ccache.tar.gz /tmp -P
      - cd /tmp
      - time tar xf ccache.tar.gz
      - rm -rf ccache.tar.gz
    rclone_setup_script:
      - mkdir -p ~/.config/rclone
      - echo "$rclone_config" > ~/.config/rclone/rclone.conf
      - mkdir -p /tmp/rom
      - cd /tmp/rom
      - curl https://raw.githubusercontent.com/I-n-o-k/aosp/main/anu -o y.sh
      - bash y.sh
      - curl https://raw.githubusercontent.com/I-n-o-k/anu/Nusantara/upload -o u.sh
      - bash u.sh
